spring:
  mvc:
    path:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/buynow?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name:  com.mysql.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    generate-ddl: true
